# backend/engine/project_exporter.py
# Project Export Package Builder
#
# Bundles all generated AutoMind outputs into a single downloadable ZIP:
#   project.zip/
#     <program_name>/
#       plc_program.st
#       hmi_dashboard.html
#       pid_diagram.html
#       generation_report.md

import io
import zipfile
from datetime import datetime


def build_project_zip(
    st_code:      str,
    hmi_html:     str,
    pid_html:     str,
    report_md:    str  = "",
    program_name: str  = "PLCProgram",
) -> bytes:
    """
    Bundle all generated outputs into a ZIP file.

    Parameters
    ----------
    st_code      : IEC 61131-3 Structured Text code string
    hmi_html     : HMI SCADA dashboard HTML string
    pid_html     : P&ID diagram HTML string
    report_md    : Generation report Markdown string (auto-generated if empty)
    program_name : Used as the top-level folder name inside the ZIP

    Returns
    -------
    bytes — ZIP file content, ready for HTTP response or disk write.
    """
    if not report_md:
        report_md = _default_report(program_name, st_code)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        base = program_name  # Top-level folder

        zf.writestr(f"{base}/plc_program.st",        st_code   or _placeholder("PLC Structured Text not generated."))
        zf.writestr(f"{base}/hmi_dashboard.html",     hmi_html  or _placeholder_html("HMI Dashboard not generated."))
        zf.writestr(f"{base}/pid_diagram.html",       pid_html  or _placeholder_html("P&ID Diagram not generated."))
        zf.writestr(f"{base}/generation_report.md",   report_md)

    return buf.getvalue()


# ── Content helpers ───────────────────────────────────────────────────────────

def _placeholder(message: str) -> str:
    return f"(* {message} *)\n"


def _placeholder_html(message: str) -> str:
    return (
        "<!DOCTYPE html><html><body style='font-family:monospace;padding:2rem;'>"
        f"<p>{message}</p></body></html>\n"
    )


def _default_report(program_name: str, st_code: str) -> str:
    """Generate a minimal Markdown report if none was supplied."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Count lines of ST code
    loc = len([ln for ln in (st_code or "").split("\n") if ln.strip()])

    lines = [
        f"# AutoMind Generation Report",
        f"",
        f"**Program:**   `{program_name}`",
        f"**Generated:** {now}",
        f"**Lines of code (non-blank):** {loc}",
        f"",
        f"## Contents",
        f"",
        f"| File | Description |",
        f"|------|-------------|",
        f"| `plc_program.st` | IEC 61131-3 Structured Text source |",
        f"| `hmi_dashboard.html` | Interactive SCADA HMI dashboard |",
        f"| `pid_diagram.html` | ISA-5.1 P&ID process diagram |",
        f"| `generation_report.md` | This report |",
        f"",
        f"## Notes",
        f"",
        f"- Generated by **AutoMind Industrial Automation Platform**",
        f"- Review all outputs before deploying to production hardware",
        f"- Validate PLC code against target PLC software (TIA Portal, CODESYS, etc.)",
    ]
    return "\n".join(lines) + "\n"


AUTOMIND_VERSION = "2.1.0"


def build_report_md(
    program_name:      str,
    engineering_score: dict,
    validation_result: dict,
    signal_map:        dict,
    warnings:          list[str],
    brand:             str  = "GENERIC",
    domain_type:       str  = "general",
    semantic_result:   dict = None,
    state_transitions: dict = None,
    llm_status:        str  = "REAL",
) -> str:
    """
    Build a detailed generation_report.md from pipeline outputs.
    Included in the project ZIP and in the stress test runner report.

    llm_status should be "REAL" when the LLM generated the code, or "STUB"
    when the deterministic fallback was used due to LLM unavailability.
    """
    now    = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    score  = engineering_score.get("engineering_score", 0)
    rating = engineering_score.get("rating", "N/A")

    sem      = semantic_result or {}
    sem_crit = sem.get("critical", [])
    sem_warn = sem.get("warning", [])

    llm_label = f"**STUB** *(LLM unavailable — deterministic fallback used)*" \
                if llm_status == "STUB" else "REAL"

    lines = [
        f"# AutoMind Generation Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Program Name** | `{program_name}` |",
        f"| **Domain Type** | {domain_type} |",
        f"| **Brand / Platform** | {brand} |",
        f"| **AutoMind Version** | {AUTOMIND_VERSION} |",
        f"| **Generated** | {now} |",
        f"| **LLM Status** | {llm_label} |",
        f"| **Engineering Score** | **{score}/100 — {rating}** |",
        f"| **Semantic Validation** | {'PASS' if not sem_crit else 'FAIL'} |",
        f"",
        f"",
        "## Engineering Score Breakdown",
        "",
        "| Criterion | Status |",
        "|-----------|--------|",
    ]
    for b in engineering_score.get("breakdown", []):
        status = "PASS" if b["passed"] else "FAIL"
        lines.append(f"| {b['criterion']} | {status} |")

    # Validation
    iec_valid   = validation_result.get("iec_valid",   "N/A")
    iec_errors  = validation_result.get("iec_errors",  [])
    iec_warnings = validation_result.get("iec_warnings", [])

    lines += [
        "",
        "## IEC Validation",
        "",
        f"**Status:** {'PASS' if iec_valid else 'FAIL'}",
    ]
    if iec_errors:
        lines += ["", "**Errors:**"]
        lines += [f"- {e}" for e in iec_errors]
    if iec_warnings:
        lines += ["", "**Warnings:**"]
        lines += [f"- {w}" for w in iec_warnings]

    # Signals
    inputs  = signal_map.get("inputs",  [])
    outputs = signal_map.get("outputs", [])
    timers  = signal_map.get("timers",  [])
    counters = signal_map.get("counters", [])

    lines += [
        "",
        "## Signal Map",
        "",
        f"| Category | Count | Names |",
        f"|----------|-------|-------|",
        f"| Inputs   | {len(inputs)}  | {', '.join(str(s) for s in inputs[:8])} |",
        f"| Outputs  | {len(outputs)} | {', '.join(str(s) for s in outputs[:8])} |",
        f"| Timers   | {len(timers)}  | {', '.join(str(s) for s in timers[:4])} |",
        f"| Counters | {len(counters)}| {', '.join(str(s) for s in counters[:4])} |",
    ]

    # Semantic validation detail
    if sem_crit or sem_warn:
        lines += ["", "## Semantic Validation"]
        if sem_crit:
            lines += ["", "**Critical Issues:**"]
            lines += [f"- {c}" for c in sem_crit]
        if sem_warn:
            lines += ["", "**Warnings:**"]
            lines += [f"- {w}" for w in sem_warn[:10]]

    # State transition validation
    if state_transitions:
        st_warn   = state_transitions.get("warnings", [])
        st_states = state_transitions.get("states_found", [])
        lines += [
            "",
            "## State Machine",
            "",
            f"States found: `{', '.join(str(s) for s in st_states)}`  ",
            f"Fault state: {'YES' if state_transitions.get('has_fault_state') else 'NO'}  ",
            f"E-Stop override: {'YES' if state_transitions.get('has_estop_override') else 'NO'}  ",
            f"Reset path: {'YES' if state_transitions.get('has_reset_path') else 'NO'}",
        ]
        if st_warn:
            lines += ["", "**State Machine Warnings:**"]
            lines += [f"- {w}" for w in st_warn[:8]]

    if warnings:
        lines += ["", "## Pipeline Warnings", ""]
        lines += [f"- {w}" for w in warnings]

    lines += [
        "",
        "---",
        f"*Generated by AutoMind Industrial Automation Platform v{AUTOMIND_VERSION}*",
    ]
    return "\n".join(lines) + "\n"
