import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import "./plc_generator_v2.css";
import { API } from '../config/api';
import { useTheme } from '../context/ThemeContext';
import LadderView from './LadderView';


const PlcGeneratorV2 = () => {
  const { theme } = useTheme();

  const [showModal, setShowModal] = useState(false);
  const [requirement, setRequirement] = useState("");
  const [programName, setProgramName] = useState("MyPLCProgram"); // New field
  const [language, setLanguage] = useState("ST"); // Default language
  const [plcBrand, setPlcBrand] = useState("siemens"); // Default brand
  const [loading, setLoading] = useState(false);
  const [generatedCode, setGeneratedCode] = useState(null);
  const [editedCode, setEditedCode] = useState(""); // User can edit code
  const [isEditing, setIsEditing] = useState(false); // Toggle edit mode
  const [showPreview, setShowPreview] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [codeHistory, setCodeHistory] = useState([]); // Keep history visible
  const [quotaExceeded, setQuotaExceeded] = useState(false);

  // Fetch History on Mount
  React.useEffect(() => {
    const fetchHistory = async () => {
      const token = localStorage.getItem("automind_token") || localStorage.getItem("token");
      const user = JSON.parse(localStorage.getItem("automind_user") || localStorage.getItem("user_details") || "{}");
      if (!token) return;

      const headers = { Authorization: `Bearer ${token}` };
      if (user.email) headers["X-User-Email"] = user.email;

      try {
        const res = await fetch(`${API}/history/`, { headers });
        if (res.ok) {
          const data = await res.json();
          // Map backend format to frontend format if needed
          const formatted = data.map(item => ({
            id: item._id || Date.now(),
            requirement: item.description,
            programName: item.program_name,
            language: item.language,
            brand: item.brand,
            code: item.code,
            rungs: item.language === 'LD' ? JSON.parse(item.code || '[]') : null, // Restore LD rungs
            timestamp: new Date(item.created_at || Date.now()).toLocaleTimeString()
          })).reverse(); // Newest first
          setCodeHistory(formatted);
        }
      } catch (e) {
        console.error("Failed to fetch history", e);
      }
    };
    fetchHistory();
  }, []);



  const languages = [
    { value: "ST", label: "Structured Text (ST)", desc: "Text-based, most popular" }
  ];

  const brands = [
    { value: "siemens", label: "Siemens SIMATIC", logo: "🔷" },
    { value: "codesys", label: "CoDeSys", logo: "⚙️" },
    { value: "allenbradley", label: "Allen-Bradley", logo: "🟨" },
    { value: "schneider", label: "Schneider Electric", logo: "🟩" }
  ];

  const handleGenerate = async () => {
    if (!requirement.trim()) return alert("Please enter a requirement!");
    if (!programName.trim()) return alert("Please enter a program name!");

    setLoading(true);
    try {
      let data;
      let result;

      const token = localStorage.getItem("automind_token") || localStorage.getItem("token");
      const user = JSON.parse(localStorage.getItem("automind_user") || "{}");
      const headers = { "Content-Type": "application/json" };
      if (token && !token.startsWith("mock-")) headers["Authorization"] = `Bearer ${token}`;
      if (user.email) headers["X-User-Email"] = user.email;

      if (language === 'LD') {
        const response = await fetch(`${API}/generate-ld`, {
          method: "POST",
          headers: headers,
          body: JSON.stringify({ domain: requirement.trim() })
        });
        if (!response.ok) throw new Error("Failed to generate LD");
        data = await response.json();

        result = {
          code: null, // LD doesn't have a single code string
          rungs: data.rungs,
          language: "LD",
          validated: true,
          timestamp: new Date().toISOString(),
          explanation: "Generated by Ladder Logic Engine",
          warnings: []
        };

      } else {
        // Use new production endpoint for ST
        const response = await fetch(`${API}/generate`, {
          method: "POST",
          headers: headers,
          body: JSON.stringify({
            brand: plcBrand,
            language: language,
            program_name: programName,
            description: requirement.trim()
          }),
        });

        if (!response.ok) {
          let errorMsg = "Unknown error";
          let status = response.status;
          try {
            const error = await response.json();
            errorMsg = error.detail || error.message || errorMsg;
          } catch {
            errorMsg = `HTTP ${status}: ${response.statusText}`;
          }
          if (status === 403 && errorMsg.toLowerCase().includes("quota")) {
            setQuotaExceeded(true);
            setLoading(false);
            setShowModal(false);
            return;
          }
          throw new Error(errorMsg);
        }
        data = await response.json();

        result = {
          code: data.code,
          language: data.language || language,
          validated: true, // Backend guarantees validity now
          timestamp: new Date().toISOString(),
          explanation: "Generated by Industrial Engine",
          warnings: data.fixes_applied || []
        };
      }

      setGeneratedCode(result);
      setEditedCode(result.code);
      setIsEditing(false);
      setShowPreview(true);
      setShowModal(false);

      setCodeHistory(prev => [{
        id: Date.now(),
        requirement: requirement,
        programName: programName,
        language: language,
        brand: plcBrand,
        code: result.code,
        timestamp: new Date().toLocaleTimeString()
      }, ...prev]);

      // Save to Backend (Fire and Forget)
      if (token) {

        fetch(`${API}/history/`, {
          method: "POST",
          headers: headers,
          body: JSON.stringify({
            program_name: programName,
            description: requirement,
            code: result.language === 'LD' ? JSON.stringify(result.rungs) : result.code, // Save rungs as JSON string
            language: language,
            brand: plcBrand,
            type: "plc"
          })
        }).catch(e => console.error("Failed to save history", e));
      }

    } catch (err) {
      console.error("Generation error:", err);
      alert(`❌ Failed to generate code:\n\n${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!generatedCode) return;

    // User requested .html format for download for some reason, 
    // maybe to retain syntax highlighting or just to open in a browser easily.
    // Creating a beautifully formatted HTML wrapper for the ST code.
    const codeToDownload = isEditing ? editedCode : generatedCode.code;

    const htmlContent = `<!DOCTYPE html>
<html>
<head>
<title>${programName} - PLC Code</title>
<style>
  body { background-color: #0f172a; color: #f8fafc; font-family: 'Consolas', monospace; padding: 2rem; }
  h2 { color: #38bdf8; font-family: 'Inter', sans-serif; }
  pre { background-color: #1e293b; padding: 1.5rem; border-radius: 8px; border: 1px solid #334155; overflow-x: auto; font-size: 14px; line-height: 1.5; }
</style>
</head>
<body>
  <h2>Model: ${programName} | Language: ${language}</h2>
  <hr style="border-color: #334155;" />
  <pre><code>${codeToDownload.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</code></pre>
</body>
</html>`;

    // Download as HTML
    const filename = `${programName || 'plc_code'}.html`;
    const element = document.createElement("a");
    const file = new Blob([htmlContent], { type: "text/html" });
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleClearHistory = () => {
    setCodeHistory([]);
    setGeneratedCode(null);
    setShowPreview(false);
    setRequirement("");
  };

  const handleTryNow = () => {
    setShowModal(true);
  };

  return (
    <div className="plc-section-v2 relative" style={{
      minHeight: 'auto',
      paddingBottom: '1rem', // Removed extra gap
      color: theme === 'dark' ? 'white' : '#1e293b',
      fontFamily: 'Inter, sans-serif',
      background: theme === 'dark'
        ? 'radial-gradient(circle at 50% 10%, #1e293b 0%, #020617 100%)'
        : 'linear-gradient(to bottom, #f8fafc, #e2e8f0)',
      position: 'relative',
      overflow: 'hidden',
      transition: 'background 0.3s, color 0.3s'
    }}>

      {/* Background Grid Effect */}
      <div style={{
        position: 'absolute', inset: 0,
        backgroundImage: theme === 'dark'
          ? 'linear-gradient(rgba(255, 255, 255, 0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255, 255, 255, 0.03) 1px, transparent 1px)'
          : 'linear-gradient(rgba(0, 0, 0, 0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(0, 0, 0, 0.03) 1px, transparent 1px)',
        backgroundSize: '40px 40px',
        pointerEvents: 'none'
      }} />

      <div style={{ position: 'relative', zIndex: 10, maxWidth: '1400px', margin: '0 auto' }}>

        {/* Quota Reached Screen */}
        {quotaExceeded ? (
          <div style={{ textAlign: 'center', padding: '80px', background: theme === 'dark' ? 'rgba(239, 68, 68, 0.1)' : 'rgba(239, 68, 68, 0.05)', border: '1px solid #ef4444', borderRadius: '24px', margin: '40px auto', maxWidth: '600px', backdropFilter: 'blur(10px)' }}>
            <h2 style={{ fontSize: '2.5rem', color: '#ef4444', marginBottom: '20px', fontWeight: 'bold' }}>⚠ Quota Reached</h2>
            <p style={{ fontSize: '1.2rem', marginBottom: '40px' }}>You have reached the 50K token quota per account. To continue generating industrial logic, please renew your subscription.</p>
            <button onClick={() => window.location.href = "mailto:contact@parijat.com?subject=Renew Automind Subscription"} style={{ padding: '16px 40px', background: '#ef4444', color: 'white', border: 'none', borderRadius: '100px', fontSize: '1.2rem', cursor: 'pointer', fontWeight: 'bold', boxShadow: '0 10px 20px -5px rgba(239, 68, 68, 0.4)' }}>Renew Subscription</button>
            <div style={{ marginTop: '20px' }}>
              <button onClick={() => setQuotaExceeded(false)} style={{ background: 'transparent', border: 'none', color: '#64748b', textDecoration: 'underline', cursor: 'pointer' }}>Go Back</button>
            </div>
          </div>
        ) : !generatedCode ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '60vh' }}>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              style={{
                background: theme === 'dark' ? 'rgba(30, 41, 59, 0.7)' : 'rgba(255, 255, 255, 0.7)',
                backdropFilter: 'blur(10px)',
                padding: '60px',
                borderRadius: '24px',
                border: theme === 'dark' ? '1px solid rgba(255, 255, 255, 0.1)' : '1px solid rgba(0, 0, 0, 0.05)',
                boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.2)',
                textAlign: 'center',
                maxWidth: '800px',
                width: '100%'
              }}
            >
              <div style={{
                background: 'linear-gradient(135deg, #0ea5e9 0%, #3b82f6 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                fontSize: '2.5rem',
                fontWeight: '800',
                marginBottom: '1rem',
                letterSpacing: '-0.02em',
                lineHeight: '1.1'
              }}>
                Industrial PLC Generator
              </div>

              <p className={`mb-10 text-lg leading-relaxed max-w-2xl mx-auto ${theme === 'dark' ? 'text-slate-400' : 'text-slate-600'}`}>
                Create production-ready code.
                <br />
                Supports Siemens, Codesys, AB, and Schneider IEC 61131-3 loops.
              </p>

              <motion.button
                whileHover={{ scale: 1.05, boxShadow: '0 20px 30px -10px rgba(14, 165, 233, 0.4)' }}
                whileTap={{ scale: 0.98 }}
                onClick={handleTryNow}
                style={{
                  padding: '18px 50px',
                  background: 'linear-gradient(to right, #0ea5e9, #2563eb)',
                  color: 'white',
                  border: 'none',
                  borderRadius: '100px',
                  fontSize: '1.25em',
                  fontWeight: '600',
                  cursor: 'pointer',
                  boxShadow: '0 10px 20px -5px rgba(14, 165, 233, 0.3)',
                  letterSpacing: '0.02em'
                }}
              >
                Start Project →
              </motion.button>

              <div style={{ marginTop: '30px', display: 'flex', justifyContent: 'center', gap: '20px', fontSize: '0.9em', color: theme === 'dark' ? '#64748b' : '#64748b' }}>
                <span>IEC 61131-3</span> • <span>Multi-Vendor</span> • <span>Validation</span> • <span>Auto-Fix</span>
              </div>
            </motion.div>
          </div>
        ) : (
          /* Workspace View */
          <div className="plc-results-container">
            {/* Header for Workspace Mode */}
            <div style={{ gridColumn: '1 / -1', marginTop: '40px', marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <h2 style={{ fontSize: '1.8rem', fontWeight: 'bold', color: theme === 'dark' ? 'white' : '#1e293b' }}>
                Industrial PLC Generator
              </h2>
              <button onClick={handleTryNow} style={{
                padding: '10px 20px',
                background: 'rgba(14, 165, 233, 0.1)',
                color: '#0ea5e9',
                border: '1px solid rgba(14, 165, 233, 0.3)',
                borderRadius: '8px',
                cursor: 'pointer'
              }}>
                + New Project
              </button>
            </div>

            {codeHistory.length > 0 && (
              <div className="plc-history-panel" style={{
                background: theme === 'dark' ? 'rgba(30, 41, 59, 0.5)' : 'rgba(255, 255, 255, 0.5)',
                backdropFilter: 'blur(10px)',
                border: theme === 'dark' ? '1px solid rgba(255, 255, 255, 0.1)' : '1px solid rgba(0, 0, 0, 0.05)'
              }}>
                <div className="history-header">
                  <h3 style={{ color: theme === 'dark' ? '#e2e8f0' : '#334155' }}>📋 Project History</h3>
                  <button className="clear-btn" onClick={handleClearHistory}>Clear</button>
                </div>
                <div className="history-list">
                  {codeHistory.map((item) => (
                    <div key={item.id} className="history-item" onClick={() => {
                      setGeneratedCode({
                        code: item.code,
                        rungs: item.rungs, // Pass restored rungs
                        language: item.language,
                        validated: true,
                        timestamp: item.timestamp,
                        explanation: "Retrieved from history",
                        warnings: []
                      });
                      setEditedCode(item.code);
                      setIsEditing(false);
                      setShowPreview(true);
                      setProgramName(item.programName);
                    }} style={{
                      background: theme === 'dark' ? 'rgba(15, 23, 42, 0.6)' : 'white',
                      color: theme === 'dark' ? '#94a3b8' : '#475569'
                    }}>
                      <div className="history-meta">
                        <strong style={{ color: theme === 'dark' ? '#f1f5f9' : '#1e293b' }}>{item.programName}</strong>
                        <span className="validated-badge">Validated</span>
                      </div>
                      <p className="history-requirement">{item.requirement.substring(0, 40)}...</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {generatedCode && (
              <div className="plc-preview-panel" style={{
                background: theme === 'dark' ? 'rgba(30, 41, 59, 0.5)' : 'rgba(255, 255, 255, 0.8)',
                backdropFilter: 'blur(10px)',
                border: theme === 'dark' ? '1px solid rgba(255, 255, 255, 0.1)' : '1px solid rgba(0, 0, 0, 0.05)'
              }}>
                <div className="preview-header">
                  <h3>✅ Production Code Ready</h3>
                  <div className="preview-meta">
                    <span className="language-tag">{generatedCode.language}</span>
                  </div>
                </div>

                {generatedCode.warnings && generatedCode.warnings.length > 0 && (
                  <div className="validation-section">
                    <h4>🔧 Auto-Fixes Applied:</h4>
                    <div className="validation-list">
                      {generatedCode.warnings.map((w, i) => (
                        <div key={i} className="validation-item tip">✓ {w}</div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="code-preview">
                  {language === 'LD' ? (
                    <LadderView rungs={generatedCode.rungs || []} />
                  ) : (
                    <div className="code-preview-inner">
                      <div className="code-header">
                        <h4>{programName}.{language === 'ST' ? 'st' : 'txt'}</h4>
                        <div className="code-actions">
                          <button className={`edit-btn ${isEditing ? 'editing' : ''}`} onClick={() => setIsEditing(!isEditing)}>
                            {isEditing ? "Done" : "Edit"}
                          </button>
                          <button style={{ background: 'transparent', color: '#38bdf8', border: '1px solid #38bdf8', padding: '4px 12px', borderRadius: '4px', fontSize: '12px', cursor: 'pointer', margin: '0 5px' }} onClick={() => setIsFullscreen(true)}>⛶ Full Screen</button>
                          <button className="copy-btn" onClick={() => {
                            navigator.clipboard.writeText(isEditing ? editedCode : generatedCode.code);
                            alert("Copied!");
                          }}>Copy</button>
                        </div>
                      </div>
                      {isEditing ? (
                        <textarea className="code-editor" value={editedCode} onChange={(e) => setEditedCode(e.target.value)} />
                      ) : (
                        <pre style={{ background: '#0f172a', border: '1px solid #334155' }}><code>{editedCode}</code></pre>
                      )}
                    </div>
                  )}
                </div>

                <div className="preview-actions" style={{ marginTop: '10px' }}>
                  <button className="download-btn" onClick={handleDownload}>💾 Download .html</button>
                </div>
              </div>
            )}
          </div>
        )}

      </div>

      <AnimatePresence>
        {showModal && (
          <motion.div className="plc-modal-overlay-v2" onClick={() => setShowModal(false)}>
            <motion.div
              className="plc-modal-v2"
              onClick={(e) => e.stopPropagation()}
              style={{
                background: theme === 'dark' ? '#1e293b' : 'white',
                color: theme === 'dark' ? 'white' : '#1e293b'
              }}
            >
              <div className="modal-header">
                <h3>New PLC Project</h3>
                <button className="close-btn" onClick={() => setShowModal(false)}>✕</button>
              </div>

              <div className="modal-content">
                <div className="input-group">
                  <label>Program Name</label>
                  <input
                    type="text"
                    value={programName}
                    onChange={(e) => setProgramName(e.target.value)}
                    placeholder="e.g. PumpControl, MainMachine"
                    className="modal-input"
                  />
                </div>

                <div className="input-group">
                  <label>Target Brand</label>
                  <div className="brand-options">
                    {brands.map(b => (
                      <button
                        key={b.value}
                        className={`brand-btn ${plcBrand === b.value ? 'active' : ''}`}
                        onClick={() => setPlcBrand(b.value)}
                      >
                        {b.logo} {b.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="input-group">
                  <label>Language</label>
                  <div className="msg-options" style={{ justifyContent: 'center' }}>
                    {languages.map(l => (
                      <button
                        key={l.value}
                        className={`lang-btn ${language === l.value ? 'active' : ''}`}
                        onClick={() => setLanguage(l.value)}
                      >
                        {l.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="input-group">
                  <label>System Description</label>
                  <textarea
                    value={requirement}
                    onChange={(e) => setRequirement(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        handleGenerate();
                      }
                    }}
                    placeholder="Describe inputs, outputs, and logic (e.g. 'Turn on motor M1 when Start button is pressed...')"
                    className="requirement-textarea"
                  />
                </div>

                <div className="modal-actions" style={{ background: theme === 'dark' ? '#1e293b' : '#f8fafc' }}>
                  <button className="btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
                  <button className="btn-primary" onClick={handleGenerate} disabled={loading}>
                    {loading ? "Generating..." : "Compile & Generate"}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {isFullscreen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={{
              position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
              background: 'rgba(15, 23, 42, 0.98)', zIndex: 9999,
              display: 'flex', flexDirection: 'column', padding: '30px'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px', alignItems: 'center' }}>
              <h2 style={{ color: 'white', margin: 0, fontSize: '24px' }}>{programName}.{language === 'ST' ? 'st' : 'txt'}</h2>
              <div>
                <button
                  onClick={() => setIsEditing(!isEditing)}
                  style={{ background: isEditing ? '#3b82f6' : 'transparent', color: 'white', border: '1px solid #3b82f6', padding: '10px 20px', borderRadius: '6px', marginRight: '15px', cursor: 'pointer', fontSize: '16px' }}
                >
                  {isEditing ? "Done Editing" : "✏️ Edit"}
                </button>
                <button onClick={handleDownload} style={{ background: '#10b981', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '6px', marginRight: '15px', cursor: 'pointer', fontSize: '16px' }}>
                  💾 Download .html
                </button>
                <button
                  onClick={() => setIsFullscreen(false)}
                  style={{ background: '#ef4444', color: 'white', border: 'none', padding: '10px 20px', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', fontSize: '16px' }}
                >
                  ✕ Close
                </button>
              </div>
            </div>

            <div style={{ flex: 1, overflow: 'hidden', display: 'flex' }}>
              {isEditing ? (
                <textarea
                  value={editedCode}
                  onChange={(e) => setEditedCode(e.target.value)}
                  style={{ width: '100%', height: '100%', background: '#1e293b', color: '#38bdf8', padding: '24px', fontFamily: '"Consolas", monospace', fontSize: '18px', lineHeight: '1.6', border: '2px solid #3b82f6', borderRadius: '8px', resize: 'none', outline: 'none' }}
                />
              ) : (
                <pre style={{ width: '100%', height: '100%', background: '#0f172a', color: '#f8fafc', padding: '24px', overflow: 'auto', borderRadius: '8px', border: '1px solid #334155', margin: 0, fontSize: '18px', lineHeight: '1.6' }}><code>{editedCode}</code></pre>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default PlcGeneratorV2;
